import type { Metadata } from 'next';

import { AuthProvider } from './(home)/AuthProvider';
import { Pretendard, Ydestreet } from './fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${Ydestreet.variable} ${Pretendard.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
